server:
  port:8088
spring:
  jpa:
    hibernate:
      ddl-auto: update
      show-sql: true
    properties: 
      hibernate: 
        dialect: org.hibernate.dialect.MySQL5Dialect
  datasource:
    url:jdbc: mysql://localhost/microservice
    username: root
    password: test
 eureka:
  client:
    register-with-eureka:true
    fetch-registry:true
